import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from './_hooks/ReactQueryProvider';
import { AuthContext } from './_context/AuthContext';

const notoSansKR = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKR.className}>
        <AuthContext>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </AuthContext>
      </body>
    </html>
  );
}
